# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.5

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /opt/logicmoo_workspace/taupl/test123/SxxMachine

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /opt/logicmoo_workspace/taupl/test123/SxxMachine

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	# $(CMAKE_COMMAND) -E cmake_progress_start /opt/logicmoo_workspace/taupl/test123/SxxMachine/CMakeFiles /opt/logicmoo_workspace/taupl/test123/SxxMachine/CMakeFiles/progress.marks
	# $(MAKE) -f CMakeFiles/Makefile2 all
	# $(CMAKE_COMMAND) -E cmake_progress_start /opt/logicmoo_workspace/taupl/test123/SxxMachine/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named SxxMachine

# Build rule for target.
SxxMachine: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 SxxMachine
.PHONY : SxxMachine

# fast build rule for target.
SxxMachine/fast:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/build
.PHONY : SxxMachine/fast

src/machine/SxxMachine/Builtins.o: src/machine/SxxMachine/Builtins.cpp.o

.PHONY : src/machine/SxxMachine/Builtins.o

# target to build an object file
src/machine/SxxMachine/Builtins.cpp.o:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Builtins.cpp.o
.PHONY : src/machine/SxxMachine/Builtins.cpp.o

src/machine/SxxMachine/Builtins.i: src/machine/SxxMachine/Builtins.cpp.i

.PHONY : src/machine/SxxMachine/Builtins.i

# target to preprocess a source file
src/machine/SxxMachine/Builtins.cpp.i:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Builtins.cpp.i
.PHONY : src/machine/SxxMachine/Builtins.cpp.i

src/machine/SxxMachine/Builtins.s: src/machine/SxxMachine/Builtins.cpp.s

.PHONY : src/machine/SxxMachine/Builtins.s

# target to generate assembly for a file
src/machine/SxxMachine/Builtins.cpp.s:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Builtins.cpp.s
.PHONY : src/machine/SxxMachine/Builtins.cpp.s

src/machine/SxxMachine/Code.o: src/machine/SxxMachine/Code.cpp.o

.PHONY : src/machine/SxxMachine/Code.o

# target to build an object file
src/machine/SxxMachine/Code.cpp.o:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Code.cpp.o
.PHONY : src/machine/SxxMachine/Code.cpp.o

src/machine/SxxMachine/Code.i: src/machine/SxxMachine/Code.cpp.i

.PHONY : src/machine/SxxMachine/Code.i

# target to preprocess a source file
src/machine/SxxMachine/Code.cpp.i:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Code.cpp.i
.PHONY : src/machine/SxxMachine/Code.cpp.i

src/machine/SxxMachine/Code.s: src/machine/SxxMachine/Code.cpp.s

.PHONY : src/machine/SxxMachine/Code.s

# target to generate assembly for a file
src/machine/SxxMachine/Code.cpp.s:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Code.cpp.s
.PHONY : src/machine/SxxMachine/Code.cpp.s

src/machine/SxxMachine/Const.o: src/machine/SxxMachine/Const.cpp.o

.PHONY : src/machine/SxxMachine/Const.o

# target to build an object file
src/machine/SxxMachine/Const.cpp.o:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Const.cpp.o
.PHONY : src/machine/SxxMachine/Const.cpp.o

src/machine/SxxMachine/Const.i: src/machine/SxxMachine/Const.cpp.i

.PHONY : src/machine/SxxMachine/Const.i

# target to preprocess a source file
src/machine/SxxMachine/Const.cpp.i:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Const.cpp.i
.PHONY : src/machine/SxxMachine/Const.cpp.i

src/machine/SxxMachine/Const.s: src/machine/SxxMachine/Const.cpp.s

.PHONY : src/machine/SxxMachine/Const.s

# target to generate assembly for a file
src/machine/SxxMachine/Const.cpp.s:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Const.cpp.s
.PHONY : src/machine/SxxMachine/Const.cpp.s

src/machine/SxxMachine/Continuation.o: src/machine/SxxMachine/Continuation.cpp.o

.PHONY : src/machine/SxxMachine/Continuation.o

# target to build an object file
src/machine/SxxMachine/Continuation.cpp.o:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Continuation.cpp.o
.PHONY : src/machine/SxxMachine/Continuation.cpp.o

src/machine/SxxMachine/Continuation.i: src/machine/SxxMachine/Continuation.cpp.i

.PHONY : src/machine/SxxMachine/Continuation.i

# target to preprocess a source file
src/machine/SxxMachine/Continuation.cpp.i:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Continuation.cpp.i
.PHONY : src/machine/SxxMachine/Continuation.cpp.i

src/machine/SxxMachine/Continuation.s: src/machine/SxxMachine/Continuation.cpp.s

.PHONY : src/machine/SxxMachine/Continuation.s

# target to generate assembly for a file
src/machine/SxxMachine/Continuation.cpp.s:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Continuation.cpp.s
.PHONY : src/machine/SxxMachine/Continuation.cpp.s

src/machine/SxxMachine/Data.o: src/machine/SxxMachine/Data.cpp.o

.PHONY : src/machine/SxxMachine/Data.o

# target to build an object file
src/machine/SxxMachine/Data.cpp.o:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Data.cpp.o
.PHONY : src/machine/SxxMachine/Data.cpp.o

src/machine/SxxMachine/Data.i: src/machine/SxxMachine/Data.cpp.i

.PHONY : src/machine/SxxMachine/Data.i

# target to preprocess a source file
src/machine/SxxMachine/Data.cpp.i:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Data.cpp.i
.PHONY : src/machine/SxxMachine/Data.cpp.i

src/machine/SxxMachine/Data.s: src/machine/SxxMachine/Data.cpp.s

.PHONY : src/machine/SxxMachine/Data.s

# target to generate assembly for a file
src/machine/SxxMachine/Data.cpp.s:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Data.cpp.s
.PHONY : src/machine/SxxMachine/Data.cpp.s

src/machine/SxxMachine/FrozenVar.o: src/machine/SxxMachine/FrozenVar.cpp.o

.PHONY : src/machine/SxxMachine/FrozenVar.o

# target to build an object file
src/machine/SxxMachine/FrozenVar.cpp.o:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/FrozenVar.cpp.o
.PHONY : src/machine/SxxMachine/FrozenVar.cpp.o

src/machine/SxxMachine/FrozenVar.i: src/machine/SxxMachine/FrozenVar.cpp.i

.PHONY : src/machine/SxxMachine/FrozenVar.i

# target to preprocess a source file
src/machine/SxxMachine/FrozenVar.cpp.i:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/FrozenVar.cpp.i
.PHONY : src/machine/SxxMachine/FrozenVar.cpp.i

src/machine/SxxMachine/FrozenVar.s: src/machine/SxxMachine/FrozenVar.cpp.s

.PHONY : src/machine/SxxMachine/FrozenVar.s

# target to generate assembly for a file
src/machine/SxxMachine/FrozenVar.cpp.s:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/FrozenVar.cpp.s
.PHONY : src/machine/SxxMachine/FrozenVar.cpp.s

src/machine/SxxMachine/Fun.o: src/machine/SxxMachine/Fun.cpp.o

.PHONY : src/machine/SxxMachine/Fun.o

# target to build an object file
src/machine/SxxMachine/Fun.cpp.o:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Fun.cpp.o
.PHONY : src/machine/SxxMachine/Fun.cpp.o

src/machine/SxxMachine/Fun.i: src/machine/SxxMachine/Fun.cpp.i

.PHONY : src/machine/SxxMachine/Fun.i

# target to preprocess a source file
src/machine/SxxMachine/Fun.cpp.i:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Fun.cpp.i
.PHONY : src/machine/SxxMachine/Fun.cpp.i

src/machine/SxxMachine/Fun.s: src/machine/SxxMachine/Fun.cpp.s

.PHONY : src/machine/SxxMachine/Fun.s

# target to generate assembly for a file
src/machine/SxxMachine/Fun.cpp.s:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Fun.cpp.s
.PHONY : src/machine/SxxMachine/Fun.cpp.s

src/machine/SxxMachine/HeapChoice.o: src/machine/SxxMachine/HeapChoice.cpp.o

.PHONY : src/machine/SxxMachine/HeapChoice.o

# target to build an object file
src/machine/SxxMachine/HeapChoice.cpp.o:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/HeapChoice.cpp.o
.PHONY : src/machine/SxxMachine/HeapChoice.cpp.o

src/machine/SxxMachine/HeapChoice.i: src/machine/SxxMachine/HeapChoice.cpp.i

.PHONY : src/machine/SxxMachine/HeapChoice.i

# target to preprocess a source file
src/machine/SxxMachine/HeapChoice.cpp.i:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/HeapChoice.cpp.i
.PHONY : src/machine/SxxMachine/HeapChoice.cpp.i

src/machine/SxxMachine/HeapChoice.s: src/machine/SxxMachine/HeapChoice.cpp.s

.PHONY : src/machine/SxxMachine/HeapChoice.s

# target to generate assembly for a file
src/machine/SxxMachine/HeapChoice.cpp.s:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/HeapChoice.cpp.s
.PHONY : src/machine/SxxMachine/HeapChoice.cpp.s

src/machine/SxxMachine/Int.o: src/machine/SxxMachine/Int.cpp.o

.PHONY : src/machine/SxxMachine/Int.o

# target to build an object file
src/machine/SxxMachine/Int.cpp.o:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Int.cpp.o
.PHONY : src/machine/SxxMachine/Int.cpp.o

src/machine/SxxMachine/Int.i: src/machine/SxxMachine/Int.cpp.i

.PHONY : src/machine/SxxMachine/Int.i

# target to preprocess a source file
src/machine/SxxMachine/Int.cpp.i:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Int.cpp.i
.PHONY : src/machine/SxxMachine/Int.cpp.i

src/machine/SxxMachine/Int.s: src/machine/SxxMachine/Int.cpp.s

.PHONY : src/machine/SxxMachine/Int.s

# target to generate assembly for a file
src/machine/SxxMachine/Int.cpp.s:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Int.cpp.s
.PHONY : src/machine/SxxMachine/Int.cpp.s

src/machine/SxxMachine/Lexer.o: src/machine/SxxMachine/Lexer.cpp.o

.PHONY : src/machine/SxxMachine/Lexer.o

# target to build an object file
src/machine/SxxMachine/Lexer.cpp.o:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Lexer.cpp.o
.PHONY : src/machine/SxxMachine/Lexer.cpp.o

src/machine/SxxMachine/Lexer.i: src/machine/SxxMachine/Lexer.cpp.i

.PHONY : src/machine/SxxMachine/Lexer.i

# target to preprocess a source file
src/machine/SxxMachine/Lexer.cpp.i:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Lexer.cpp.i
.PHONY : src/machine/SxxMachine/Lexer.cpp.i

src/machine/SxxMachine/Lexer.s: src/machine/SxxMachine/Lexer.cpp.s

.PHONY : src/machine/SxxMachine/Lexer.s

# target to generate assembly for a file
src/machine/SxxMachine/Lexer.cpp.s:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Lexer.cpp.s
.PHONY : src/machine/SxxMachine/Lexer.cpp.s

src/machine/SxxMachine/Metaterm.o: src/machine/SxxMachine/Metaterm.cpp.o

.PHONY : src/machine/SxxMachine/Metaterm.o

# target to build an object file
src/machine/SxxMachine/Metaterm.cpp.o:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Metaterm.cpp.o
.PHONY : src/machine/SxxMachine/Metaterm.cpp.o

src/machine/SxxMachine/Metaterm.i: src/machine/SxxMachine/Metaterm.cpp.i

.PHONY : src/machine/SxxMachine/Metaterm.i

# target to preprocess a source file
src/machine/SxxMachine/Metaterm.cpp.i:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Metaterm.cpp.i
.PHONY : src/machine/SxxMachine/Metaterm.cpp.i

src/machine/SxxMachine/Metaterm.s: src/machine/SxxMachine/Metaterm.cpp.s

.PHONY : src/machine/SxxMachine/Metaterm.s

# target to generate assembly for a file
src/machine/SxxMachine/Metaterm.cpp.s:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Metaterm.cpp.s
.PHONY : src/machine/SxxMachine/Metaterm.cpp.s

src/machine/SxxMachine/Operation.o: src/machine/SxxMachine/Operation.cpp.o

.PHONY : src/machine/SxxMachine/Operation.o

# target to build an object file
src/machine/SxxMachine/Operation.cpp.o:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Operation.cpp.o
.PHONY : src/machine/SxxMachine/Operation.cpp.o

src/machine/SxxMachine/Operation.i: src/machine/SxxMachine/Operation.cpp.i

.PHONY : src/machine/SxxMachine/Operation.i

# target to preprocess a source file
src/machine/SxxMachine/Operation.cpp.i:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Operation.cpp.i
.PHONY : src/machine/SxxMachine/Operation.cpp.i

src/machine/SxxMachine/Operation.s: src/machine/SxxMachine/Operation.cpp.s

.PHONY : src/machine/SxxMachine/Operation.s

# target to generate assembly for a file
src/machine/SxxMachine/Operation.cpp.s:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Operation.cpp.s
.PHONY : src/machine/SxxMachine/Operation.cpp.s

src/machine/SxxMachine/PredTable.o: src/machine/SxxMachine/PredTable.cpp.o

.PHONY : src/machine/SxxMachine/PredTable.o

# target to build an object file
src/machine/SxxMachine/PredTable.cpp.o:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/PredTable.cpp.o
.PHONY : src/machine/SxxMachine/PredTable.cpp.o

src/machine/SxxMachine/PredTable.i: src/machine/SxxMachine/PredTable.cpp.i

.PHONY : src/machine/SxxMachine/PredTable.i

# target to preprocess a source file
src/machine/SxxMachine/PredTable.cpp.i:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/PredTable.cpp.i
.PHONY : src/machine/SxxMachine/PredTable.cpp.i

src/machine/SxxMachine/PredTable.s: src/machine/SxxMachine/PredTable.cpp.s

.PHONY : src/machine/SxxMachine/PredTable.s

# target to generate assembly for a file
src/machine/SxxMachine/PredTable.cpp.s:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/PredTable.cpp.s
.PHONY : src/machine/SxxMachine/PredTable.cpp.s

src/machine/SxxMachine/Prolog.o: src/machine/SxxMachine/Prolog.cpp.o

.PHONY : src/machine/SxxMachine/Prolog.o

# target to build an object file
src/machine/SxxMachine/Prolog.cpp.o:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Prolog.cpp.o
.PHONY : src/machine/SxxMachine/Prolog.cpp.o

src/machine/SxxMachine/Prolog.i: src/machine/SxxMachine/Prolog.cpp.i

.PHONY : src/machine/SxxMachine/Prolog.i

# target to preprocess a source file
src/machine/SxxMachine/Prolog.cpp.i:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Prolog.cpp.i
.PHONY : src/machine/SxxMachine/Prolog.cpp.i

src/machine/SxxMachine/Prolog.s: src/machine/SxxMachine/Prolog.cpp.s

.PHONY : src/machine/SxxMachine/Prolog.s

# target to generate assembly for a file
src/machine/SxxMachine/Prolog.cpp.s:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Prolog.cpp.s
.PHONY : src/machine/SxxMachine/Prolog.cpp.s

src/machine/SxxMachine/Real.o: src/machine/SxxMachine/Real.cpp.o

.PHONY : src/machine/SxxMachine/Real.o

# target to build an object file
src/machine/SxxMachine/Real.cpp.o:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Real.cpp.o
.PHONY : src/machine/SxxMachine/Real.cpp.o

src/machine/SxxMachine/Real.i: src/machine/SxxMachine/Real.cpp.i

.PHONY : src/machine/SxxMachine/Real.i

# target to preprocess a source file
src/machine/SxxMachine/Real.cpp.i:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Real.cpp.i
.PHONY : src/machine/SxxMachine/Real.cpp.i

src/machine/SxxMachine/Real.s: src/machine/SxxMachine/Real.cpp.s

.PHONY : src/machine/SxxMachine/Real.s

# target to generate assembly for a file
src/machine/SxxMachine/Real.cpp.s:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Real.cpp.s
.PHONY : src/machine/SxxMachine/Real.cpp.s

src/machine/SxxMachine/Term.o: src/machine/SxxMachine/Term.cpp.o

.PHONY : src/machine/SxxMachine/Term.o

# target to build an object file
src/machine/SxxMachine/Term.cpp.o:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Term.cpp.o
.PHONY : src/machine/SxxMachine/Term.cpp.o

src/machine/SxxMachine/Term.i: src/machine/SxxMachine/Term.cpp.i

.PHONY : src/machine/SxxMachine/Term.i

# target to preprocess a source file
src/machine/SxxMachine/Term.cpp.i:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Term.cpp.i
.PHONY : src/machine/SxxMachine/Term.cpp.i

src/machine/SxxMachine/Term.s: src/machine/SxxMachine/Term.cpp.s

.PHONY : src/machine/SxxMachine/Term.s

# target to generate assembly for a file
src/machine/SxxMachine/Term.cpp.s:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Term.cpp.s
.PHONY : src/machine/SxxMachine/Term.cpp.s

src/machine/SxxMachine/Var.o: src/machine/SxxMachine/Var.cpp.o

.PHONY : src/machine/SxxMachine/Var.o

# target to build an object file
src/machine/SxxMachine/Var.cpp.o:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Var.cpp.o
.PHONY : src/machine/SxxMachine/Var.cpp.o

src/machine/SxxMachine/Var.i: src/machine/SxxMachine/Var.cpp.i

.PHONY : src/machine/SxxMachine/Var.i

# target to preprocess a source file
src/machine/SxxMachine/Var.cpp.i:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Var.cpp.i
.PHONY : src/machine/SxxMachine/Var.cpp.i

src/machine/SxxMachine/Var.s: src/machine/SxxMachine/Var.cpp.s

.PHONY : src/machine/SxxMachine/Var.s

# target to generate assembly for a file
src/machine/SxxMachine/Var.cpp.s:
	$(MAKE) -f CMakeFiles/SxxMachine.dir/build.make CMakeFiles/SxxMachine.dir/src/machine/SxxMachine/Var.cpp.s
.PHONY : src/machine/SxxMachine/Var.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... SxxMachine"
	@echo "... rebuild_cache"
	@echo "... src/machine/SxxMachine/Builtins.o"
	@echo "... src/machine/SxxMachine/Builtins.i"
	@echo "... src/machine/SxxMachine/Builtins.s"
	@echo "... src/machine/SxxMachine/Code.o"
	@echo "... src/machine/SxxMachine/Code.i"
	@echo "... src/machine/SxxMachine/Code.s"
	@echo "... src/machine/SxxMachine/Const.o"
	@echo "... src/machine/SxxMachine/Const.i"
	@echo "... src/machine/SxxMachine/Const.s"
	@echo "... src/machine/SxxMachine/Continuation.o"
	@echo "... src/machine/SxxMachine/Continuation.i"
	@echo "... src/machine/SxxMachine/Continuation.s"
	@echo "... src/machine/SxxMachine/Data.o"
	@echo "... src/machine/SxxMachine/Data.i"
	@echo "... src/machine/SxxMachine/Data.s"
	@echo "... src/machine/SxxMachine/FrozenVar.o"
	@echo "... src/machine/SxxMachine/FrozenVar.i"
	@echo "... src/machine/SxxMachine/FrozenVar.s"
	@echo "... src/machine/SxxMachine/Fun.o"
	@echo "... src/machine/SxxMachine/Fun.i"
	@echo "... src/machine/SxxMachine/Fun.s"
	@echo "... src/machine/SxxMachine/HeapChoice.o"
	@echo "... src/machine/SxxMachine/HeapChoice.i"
	@echo "... src/machine/SxxMachine/HeapChoice.s"
	@echo "... src/machine/SxxMachine/Int.o"
	@echo "... src/machine/SxxMachine/Int.i"
	@echo "... src/machine/SxxMachine/Int.s"
	@echo "... src/machine/SxxMachine/Lexer.o"
	@echo "... src/machine/SxxMachine/Lexer.i"
	@echo "... src/machine/SxxMachine/Lexer.s"
	@echo "... src/machine/SxxMachine/Metaterm.o"
	@echo "... src/machine/SxxMachine/Metaterm.i"
	@echo "... src/machine/SxxMachine/Metaterm.s"
	@echo "... src/machine/SxxMachine/Operation.o"
	@echo "... src/machine/SxxMachine/Operation.i"
	@echo "... src/machine/SxxMachine/Operation.s"
	@echo "... src/machine/SxxMachine/PredTable.o"
	@echo "... src/machine/SxxMachine/PredTable.i"
	@echo "... src/machine/SxxMachine/PredTable.s"
	@echo "... src/machine/SxxMachine/Prolog.o"
	@echo "... src/machine/SxxMachine/Prolog.i"
	@echo "... src/machine/SxxMachine/Prolog.s"
	@echo "... src/machine/SxxMachine/Real.o"
	@echo "... src/machine/SxxMachine/Real.i"
	@echo "... src/machine/SxxMachine/Real.s"
	@echo "... src/machine/SxxMachine/Term.o"
	@echo "... src/machine/SxxMachine/Term.i"
	@echo "... src/machine/SxxMachine/Term.s"
	@echo "... src/machine/SxxMachine/Var.o"
	@echo "... src/machine/SxxMachine/Var.i"
	@echo "... src/machine/SxxMachine/Var.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	#$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

